### ISSUE TITLE
Crash TransactionTooLargeException on big file

### ISSUE THREAD

**Issue by LoHub** [FossifyOrg/Notes#77]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Notes/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.0

### Affected Android/Custom ROM version

Android 15

### Affected device model

Pixel

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open a huge file (in my case 240 kB)
2. Add a new note
3. Switch between foreground and background many times (sorry didn't identify the exact good trigger, hope log will help)

### Expected behavior

No crash with log bellow.

### Actual behavior

App crash

### Additional information

```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241105.007/2024110700:user/release-keys
flags: dev options enabled
package: org.fossify.notes:3, targetSdk 34
process: org.fossify.notes
processUptime: 3276 + 223 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 726948 bytes
Bundle stats:
  android:viewHierarchyState [size=1612]
    android:views [size=1564]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=724608]
    android:support:activity-result [size=1176]
    android:support:fragments [size=723056]
      fragment_5875259c-a669-4a51-a504-c306102bfae0 [size=722712]
        viewState [size=241320]
          0x7f0903aa [size=240624]
        savedInstanceState [size=480760]
          text [size=480728]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.TransactionTooLargeException: data parcel size 726948 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1527)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:101)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 10 more
```

**Comment by Aga-C** [comment]
Is this file a multiline text file, or everything's in a one line?

**Comment by Aga-C** [comment]
I've found a 300 kB text file, and I was able to reproduce it. On my Android 14, with a few notes, I couldn't even open Notes app after importing this file.

**Comment by Aga-C** [comment]
I've found a 390 kB text file, and I was able to reproduce it. On my Android 14, with a few notes, I couldn't even open Notes app after importing this file.

**Comment by Aga-C** [comment]
I've tested around a bit, and it seems to be the same issue as https://github.com/FossifyOrg/Notes/issues/73.
